baseURL = 'http://umagp.com/'
languageCode = 'en-us'
title = 'umagp'
theme = 'ananke'
publishDir = 'docs'
[menu]
[[menu.main]]
  identifier = 'fibrary'
  name = 'fibrary'
  url = 'https://fibrary.glide.page'
  weight = -110
[[menu.main]]
  identifier = 'resume'
  name = 'resume'
  url = 'https://lesliehuynhresume.glide.page/'
  weight = -110
[[params.ananke_socials]]
  name = 'twitter'
  follow = false
[[params.ananke_socials]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/lesliehuynh/' 
